# Example configuration for HoverNet-Cell-Segmentation

# comment and project setup for wandb
logging:
  mode: offline                    # "online" or "offline" [str]
  project: UNIonPannuke                 # Name of project to use [str]
  notes:                    # Notes about the run, verbose description [str]
  log_comment:              # Comment to add to name the local logging folder [str]
  tags:                     # List of tags, e.g., ["baseline", "run1"] [str]
    - "tag1"
    - "tag2"
    - "..."
  wandb_dir: "/home/xijiexu/clone/CellViT/log"               # Direcotry to store the wandb file. CAREFUL: Directory must exists [str]
  log_dir: "/home/xijiexu/clone/CellViT/log"                 # Direcotry to store all logging related files and outputs [str]
  level: "info"                   # Level of logging must be either ["critical", "error", "warning", "info", "debug"] [str]
  log_images:               # If images should be logged to WandB for this run. [bool] [Optional, defaults to False]
  group:                    # WandB group tag [str] [Optional, defaults to None]

# seeding
random_seed: 19             # Seed for numpy, pytorch etc. [int]

# hardware
gpu: 1                       # Number of GPU to run experiment on [int]

# setting paths and dataset
data:
  dataset: Pannuke                 # Name of dataset, currently supported: PanNuke, Conic. Select your dataset and the script will autoamtically select the corresponding experiment [str]
  dataset_path: "/data/xijiexu/pannuke_cellvit/"            # Path to dataset, compare ./docs/readmes/pannuke.md for further details [str]
  train_folds: [0,1]        # List of fold Numbers to use for training [list[int]]
  val_split: 0.2               # Percentage of training set that should be used for validation. Either val_split or val_fold must be provided, not both. [float]
  # val_folds:                # List of fold Numbers to use for validation [list[int]]
  test_folds: [2]              # List of fold Numbers to use for final testing [list[int]]
  num_nuclei_classes: 6      # Number of different nuclei classes (including background!, e.g. 5 nuclei classes + background = 6) [int]
  num_tissue_classes: 19
  input_shape: 256             # Input shape of data. [int] [Optional, defaults to 256]

# model options
model:
  backbone: UNI                # Backbone Type: Options are: default, ViT256, SAM-B, SAM-L, SAM-H, UNI

model_path: "/home/xijiexu/clone/CellViT/log/saved_model/"
eval_checkpoint: "pretrainedDecoder.pth"           # Either select "best_checkpoint.pth", "latest_checkpoint.pth" or one of the intermediate checkpoint names, e.g., "checkpoint_100.pth"
