logging:
  level: info
model:
  path: /home/xijiexu/clone/CellViT/log/saved_model/UNIonPannuke.pth
  num_nuclei_classes: 6
  num_tissue_classes: 19
data:
  dataset: Conic
  dataset_path: /data/xijiexu/conic_cellvit
  test_folds:
  - 1
  input_shape: 256
training:
  batch_size: 8
  mixed_precision: null
transformations:
  normalize:
    mean:
    - 0.5
    - 0.5
    - 0.5
    std:
    - 0.5
    - 0.5
    - 0.5
